#!/bin/sh
while read file
do
    echo "file: $file"
    case "$1" in
        "C-d")
            mv "$file" ~/.trash ;;
        "C-r")
            convert -rotate 90 "$file" "$file" ;;
        "C-c")
            echo -n "$file" | xclip -selection clipboard ;;
        "C-t")
            echo "$file" ;;
        "C-m")
            mv "$file" ~/Documents/images/2016/ ;;
        "C-w")
            nitrogen --save --set-zoom-fill "$file" ;;
    esac
done
