#!/bin/sh
# to test:
# ./path/to/keyhandler "C-m" < foo.txt
# where foo.txt is a file with name for each photo file per line.
if [[ $1 == "C-m" ]]
then
   dirpath=$HOME/
   while [[ "$dirpath" != *\.\/ ]]
   do
       echo "dirpath is: $dirpath"
       chunk="`ls -pa $dirpath | grep / | dmenu -i -l 8 -p "$dirpath:"`"
       echo "current chunk is: $chunk"
       if [[ $chunk == './' ]]; then
           break
       elif [[ $chunk == '../' ]]; then
           parentdir=`dirname $dirpath`
           dirpath=`realpath $parentdir`
           dirpath=$dirpath/
       elif [[ -n $chunk ]]; then
           dirpath="$dirpath$chunk"
           echo "yup, folder is existing, updated dirpath: $dirpath"
       else
           echo "folder selection interrupted, exiting program..."
           exit 0
       fi
   done
   printf "\ndest folder is $dirpath\n\n"
fi


while read file
do
    echo "file: $file"
    case "$1" in
        "C-d")
              mv "$file" ~/.trash ;;
        "C-r")
            convert -rotate 90 "$file" "$file" ;;
        "C-c")
            echo -n "$file" | xclip -selection clipboard ;;
        "C-n")
            IFS='/'; arrIN=($file); unset IFS;
            echo "copying file name: ${arrIN[-1]}"
            echo -n ${arrIN[-1]} | xclip -selection clipboard ;;
        "C-h")
            echo $'options:\nC-x is the prefix' \
                 $'\nC-d: DELETE: move file to ~/.trash' \
                 $'\nC-r: ROTATE: rotate file 90 degrees' \
                 $'\nC-c: COPY: copy file PATH to clipboard' \
                 $'\nC-n: NAME: copy file NAME to clipboard' \
                 $'\nC-h: HELP: print this help message' \
                 $'\nC-e: ECHO: echo the marked files' \
                 $'\nC-m: MOVE: move files to selected dmenu directory' \
                 $'\nC-w: NITROGEN: ???'
            ;;
        "C-e")
            echo "$file" ;;
        "C-m")
            mv "$file" $dirpath ;;
        "C-w")
            nitrogen --save --set-zoom-fill "$file" ;;
        *)
            echo "not yet implemented: $1" ;;
    esac
done
