# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.devices.lvm = {
    device = "/dev/disk/by-uuid/c12edada-d8f4-4652-83ee-d272855e8a6d";
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    options = [ "umask=0077" "defaults" ];
    device = "/dev/disk/by-uuid/1436-8476";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/459eec15-17b7-4254-a737-7a684af23c42";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e39fc2fb-63bd-41d0-bfa6-d06168e6f322"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
# lsblk --fs
# NAME             FSTYPE      FSVER            LABEL                      UUID                                   FSAVAIL FSUSE% MOUNTPOINTS
# loop0            squashfs    4.0                                                                                      0   100% /nix/.ro-store
# sda                                                                                                                            
# ├─sda1           vfat        FAT32            ESP                        1436-8476                               481.4M     6% /mnt/boot
# └─sda2           crypto_LUKS 2                                           c12edada-d8f4-4652-83ee-d272855e8a6d                  
#   └─lvm          LVM2_member LVM2 001                                    XReyvW-Hdmx-volB-0kQR-cGTG-3D8c-8wTjbY                
#     ├─MyVol-swap swap        1                                           e39fc2fb-63bd-41d0-bfa6-d06168e6f322                  [SWAP]
#     └─MyVol-root ext4        1.0                                         459eec15-17b7-4254-a737-7a684af23c42    398.2G     1% /mnt
# sdb              iso9660     Joliet Extension nixos-minimal-24.05-x86_64 1980-01-01-00-00-00-00                                
# ├─sdb1           iso9660     Joliet Extension nixos-minimal-24.05-x86_64 1980-01-01-00-00-00-00                       0   100% /iso
# └─sdb2           vfat        FAT12            EFIBOOT                    1234-5678                                             
